services:
  backend:
    build:
      context: ./backend
    container_name: transport-martinique-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
    container_name: transport-martinique-frontend
    depends_on:
      - backend
    environment:
      - BACKEND_INTERNAL_URL=http://backend:8000
    ports:
      - "3000:3000"
